name: Deploy Frontend to Raspberry Pi

on:
  push:
    branches: [ main ] # oder master, je nach Repo-Konfiguration

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Anpassen an deine Node-Version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --configuration=production

      # 1) Kopiere die lokalen Build-Artefakte auf den Raspi nach /tmp/cometa-frontend
      - name: Upload build artifacts to Raspberry Pi
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.RASPI_HOST }}
          username: ${{ secrets.RASPI_USER }}        # z.B. "wolf"
          key: ${{ secrets.RASPI_SSH_KEY }}
          source: "dist/cometa/browser/*"           # Pfad anpassen, wenn dein Build-Ordner anders heißt
          target: "/tmp/cometa-frontend"
          strip_components: 3

      # 2) Verschiebe vom /tmp-Verzeichnis nach /var/www
      - name: Move files to /var/www/cometa via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.RASPI_HOST }}
          username: ${{ secrets.RASPI_USER }}        # z.B. "wolf"
          key: ${{ secrets.RASPI_SSH_KEY }}
          port: 22
          script: |
            mkdir -p /var/www/cometa
            rm -rf /var/www/cometa/*
            cp -r /tmp/cometa-frontend/* /var/www/cometa/
            rm -rf /tmp/cometa-frontend
